config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  city       :string
#  company    :string
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Customer < ApplicationRecord
    validates_presence_of :email, message: 'This field is required'
    validates_uniqueness_of :email, message: 'This email has already been taken'

    validates_presence_of :city, message: 'This field is required'
    validates_presence_of :company, message: 'This field is required'
    validates_presence_of :name, message: 'This field is required'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  jti                    :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_jti                   (jti) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
    include Devise::JWT::RevocationStrategies::JTIMatcher

    devise :database_authenticatable, :jwt_authenticatable, :registerable,
     :recoverable, :rememberable, :validatable, jwt_revocation_strategy: self
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email, :city, :company)
    end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div class="container">
  <div class=" text-center mt-5 ">
    <h1>Customer Info</h1>
  </div>
    <div class="row ">
      <div class="col-lg-7 mx-auto">
        <div class="card mt-2 mx-auto p-4 bg-light">
          <div class="card-body bg-light">
            <div class="container">
              <%= form_with(model: customer, html: {id: "contact-form"}) do |form| %>
                <% if customer.errors.any? %>
                  <div id="error_explanation">
                  <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
                  <% customer.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :name %>
                      <%= form.text_field :name, class: "form-control" %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :email %>
                      <%= form.text_field :email, class: "form-control" %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :city %>
                      <%= form.text_field :city, class: "form-control" %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :company %>
                      <%= form.text_field :company, class: "form-control" %>
                    </div>
                  </div>
                  </div>
                  <br/>
                  <div class="actions">
                    <div class="col-md-6"> 
                      <input type="submit" class="btn btn-success btn-send pt-2 btn-block " value="Send"> 
                      <%= link_to "Back", customers_path, :class => "btn btn-secondary text-white" %>
                    </div>
                  </div>
                </div>
              <% end %>
          </div>
        </div>
      </div> 
    </div> 
  </div>
</div>

app/views/customers/edit.html.erb
<%= render 'form', customer: @customer %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class="container">
<h1>Customers</h1>

<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th class="table-dark">#</th>
      <th class="table-dark">Name</th>
      <th class="table-dark">Email</th>
      <th class="table-dark">City</th>
      <th class="table-dark">Company</th>
      <th class="table-dark" colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.city %></td>
        <td><%= customer.company %></td>
        <td class="text-center"><%= link_to 'Show', customer, class:"btn-sm btn-info text-white text-decoration-none" %></td>
        <td class="text-center"><%= link_to 'Edit', edit_customer_path(customer), class:"btn-sm btn-warning text-white text-decoration-none" %></td>
        <td class="text-center"><%= link_to "Delete", destroy_customer_path(id: customer.id), class:"btn-sm btn-danger text-decoration-none" %> </td>
        </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to 'New Customer', new_customer_path, class:"btn-sm btn-primary text-white text-decoration-none" %>
</div>
<div class="d-flex justify-content-center mt-2 ">
  <%= will_paginate @customers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/customers/new.html.erb
<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<br>
<br>
<div class="container-fluid">
  <div class="row ">
    <div class="col-lg-7 mx-auto">
      <div class="mt-2 mx-auto p-4">
        <div class="card-body bg-light">
          <div class="container">
            <div class=" text-center mt-5 ">
              <h1>Customer Info</h1>
            </div>
            <table class="table table-striped table-bordered">
              <tbody class="thead-dark text-center">
                <tr>
                  <th>#</th>
                  <th>Name</th>
                </tr>
                <tr>
                  <th><%= @customer.id %></th>
                  <th><%= @customer.name %></th>
                </tr>
                <tr>
                  <th>City</th>
                  <th>Company</th>
                </tr>
                <tr>
                  <th><%= @customer.city  %></th>
                  <th><%= @customer.company %></th>
                </tr>
              </tbody>
            </table>
            <table class="table table-striped table-bordered">
              <tbody class="thead-dark text-center">
                <tr>
                  <th><%= link_to 'Edit', edit_customer_path(@customer), class:"btn btn-success text-white text-decoration-none" %></th>
                  <th><%= link_to 'Back', customers_path, class:"btn btn-secondary text-white text-decoration-none" %></th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div> 
    </div> 
  </div>
</div>

<br/><br/><br/><br/><br/>

app/views/home/index.html.erb
<main>
    
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Album example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
      </p>
    </div>
  </div>
</section>
<br>
<br>
<br>



</div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
      <style>
        .show{
          display: none;
        }
      </style>
    <% else %>
      <style>
        .hide{
            display: none;
          }
      </style>
    <% end %>
    <%= javascript_pack_tag 'application', 'components/navigation_menu' %>
    <br>
    
    <%= yield %>
  
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <br/>
    <br/>
    <br/>
    <br/>
    
    <br/>
    <%= javascript_pack_tag 'application', 'components/footer' %>
    </main>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
    <%= stylesheet_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>